coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: false

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true