services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    environment:
      - TARGET_HOST=host.docker.internal:8080
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Test1234
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: