name: Feature Request
description: Create a new feature request with BDD specs
title: "[Feature] "
labels: [feature]
body:
  - type: input
    id: epic
    attributes:
      label: Epic / User Story ID (optional)
      placeholder: e.g. BMS-123

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Describe the feature from the user's perspective (BDD format recommended)
      placeholder: |
        As a [role],
        I want to [do something],
        So that [benefit].

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      placeholder: Any technical notes or context

  - type: textarea
    id: scenarios
    attributes:
      label: Acceptance Criteria / BDD Scenarios
      description: List Given/When/Then scenarios
      placeholder: |
        Scenario: Login with valid credentials
          Given [setup]
          When [action]
          Then [assertions]
