server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/bms_db
    username: bms_user
    password: bms_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always