FROM prom/prometheus:latest
# Add envsubst for variable substitution
RUN apk --no-cache add gettext
COPY prometheus.template.yml /etc/prometheus/prometheus.template.yml
ENTRYPOINT ["/bin/sh", "-c", "envsubst < /etc/prometheus/prometheus.template.yml > /etc/prometheus/prometheus.yml && /bin/prometheus --config.file=/etc/prometheus/prometheus.yml"]