name: ReviewDog - Ktlint & Detekt

on:
  pull_request:

jobs:
  lint:
    name: ktlint + detekt
    runs-on: ubuntu-latest

    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: 'warning'
          fail_on_error: 'false'
